//! Free-model pool handler (OpenRouter / Zenmux)
//!
//! Configured with:
//! - "reasoning_effort": "none"
//! - "max_tokens": 16000
//!
//! Supports 8 parallel model candidates.

use super::template::WaveTemplate;

pub const FREE_MODELS: &[&str] = &[
    "inclusionai/ling-3.0-flash-sante:free",
    "liquid/lfm-2.5-2.6b:free",
    "dots-studio/dots-3-note-preview:free",
    "z-ai/glm-4.7-flash-free",
    "google/gemini-2.0-flash-lite-preview-02-05:free",
    "meta-llama/llama-3.3-70b-instruct:free",
    "deepseek/deepseek-r1:free",
    "qwen/qwen-2.5-coder-32b-instruct:free",
];

pub struct LlmPool;

impl LlmPool {
    /// Generate candidate templates from free model pool specifications
    pub fn generate_candidates(prompt: &str, arms: usize) -> Vec<WaveTemplate> {
        let count = arms.clamp(1, 8);
        let mut candidates = Vec::with_capacity(count);

        for i in 0..count {
            let model = FREE_MODELS[i % FREE_MODELS.len()];
            let label = format!(
                "free-arm-{}-{}",
                i + 1,
                model
                    .split('/')
                    .next_back()
                    .unwrap_or(model)
                    .replace(':', "-")
            );
            let keywords = prompt
                .split_whitespace()
                .map(|s| {
                    s.trim_matches(|c: char| !c.is_alphanumeric())
                        .to_lowercase()
                })
                .filter(|s| !s.is_empty())
                .collect();

            let code = format!(
                "WRITE||src/bin/arm_{}.rs@@@// Generated by free model: {}\n// Task: {}\nfn main() {{\n    println!(\"Hello from {}\");\n}}\n",
                i + 1, model, prompt, label
            );

            candidates.push(WaveTemplate::new(
                i + 1,
                label,
                keywords,
                code,
                vec!["rust".to_string()],
                0.80,
            ));
        }

        candidates
    }

    /// Render OpenRouter API payload JSON
    pub fn build_openrouter_payload(model: &str, prompt: &str) -> String {
        serde_json::json!({
            "model": model,
            "messages": [
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            "reasoning_effort": "none",
            "max_tokens": 16000
        })
        .to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_llm_pool_candidates() {
        let candidates = LlmPool::generate_candidates("rust cli app", 4);
        assert_eq!(candidates.len(), 4);
        assert!(candidates[0].label.contains("free-arm-1"));

        let payload = LlmPool::build_openrouter_payload(FREE_MODELS[0], "rust cli app");
        assert!(payload.contains("reasoning_effort"));
        assert!(payload.contains("16000"));
    }
}
