name: CI

on:
  push:
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4 # stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae # v2
        with:
          workspaces: |
            .
            bio-binaries
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --locked --all-targets -- -D warnings
      - name: Octopus tests
        run: cargo test --locked -j1
      - name: Bio tests
        run: cargo test --manifest-path bio-binaries/Cargo.toml --locked -j1
      - name: Release build
        run: cargo build --release --locked -j1
