name: CI

on:
  push:
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            .
            bio-binaries
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --locked --all-targets -- -D warnings
      - name: Octopus tests
        run: cargo test --locked -j1
      - name: Bio tests
        run: cargo test --manifest-path bio-binaries/Cargo.toml --locked -j1
      - name: Release build
        run: cargo build --release --locked -j1
